env:
  browser: true
  node: true
globals:
  Uint8Array: true
  DataView: true
  Buffer: true
  TextDecoder: true

parserOptions:
  ecmaVersion: 6

extends: 'eslint:recommended'

rules:
  quotes: ['error', 'single']
