language: node_js
sudo: false
install:
  - npm install -g codecov
  - yarn install --pure-lockfile
node_js:
  - "node"
  - "lts/*"
  - "6"

script:
  - yarn lint
  - yarn test
after_success:
  - codecov
